# Generated by Django 6.0.3 on 2026-03-27 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_assistantconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistantconfig',
            options={'permissions': (('rollback_assistantconfig', 'Can rollback assistant configuration'), ('manage_advanced_assistantconfig', 'Can manage advanced assistant settings')), 'verbose_name': 'Assistant Configuration', 'verbose_name_plural': 'Assistant Configuration'},
        ),
        migrations.CreateModel(
            name='AssistantConfigHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField()),
                ('model_name', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('changed_by', models.CharField(blank=True, max_length=150)),
                ('change_reason', models.CharField(choices=[('update', 'Update'), ('rollback', 'Rollback')], default='update', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='chat.assistantconfig')),
            ],
            options={
                'verbose_name': 'Assistant Configuration History',
                'verbose_name_plural': 'Assistant Configuration History',
                'ordering': ['-created_at'],
            },
        ),
    ]
