# Generated by Django 6.0.3 on 2026-03-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_assistantconfig_options_assistantconfighistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantconfig',
            name='compatibility_score_threshold',
            field=models.PositiveSmallIntegerField(default=58),
        ),
        migrations.AddField(
            model_name='assistantconfig',
            name='enable_compatibility_engine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistantconfig',
            name='enable_face_reading_engine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistantconfig',
            name='enable_fengshui_engine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistantconfig',
            name='enable_house_numerology_engine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistantconfig',
            name='enable_palm_reading_engine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistantconfig',
            name='enable_vehicle_numerology_engine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistantconfig',
            name='engine_operator_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assistantconfighistory',
            name='compatibility_score_threshold',
            field=models.PositiveSmallIntegerField(default=58),
        ),
        migrations.AddField(
            model_name='assistantconfighistory',
            name='enable_compatibility_engine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistantconfighistory',
            name='enable_face_reading_engine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistantconfighistory',
            name='enable_fengshui_engine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistantconfighistory',
            name='enable_house_numerology_engine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistantconfighistory',
            name='enable_palm_reading_engine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistantconfighistory',
            name='enable_vehicle_numerology_engine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistantconfighistory',
            name='engine_operator_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assistantconfig',
            name='system_prompt',
            field=models.TextField(default='អ្នកគឺជា "យាយមុន្នី" ជាអ្នកមើលជោគជាតាអាយុ ៨០ ឆ្នាំ។ យាយមើលតែបែបខ្មែរ និងបែបចិនប៉ុណ្ណោះ។ យាយនិយាយសាមញ្ញ ទន់ភ្លន់ កក់ក្តៅ ហើយដូចជាមនុស្សចាស់ដែលមានបទពិសោធន៍ជីវិតច្រើន។\n\nបរិបទសំខាន់\n- យាយនិងអ្នកប្រើកំពុងជជែកតាមប្រព័ន្ធអនឡាញ (chat)\n- កុំប្រើពាក្យបែបជួបផ្ទាល់ ដូចជា "មកអង្គុយជិតយាយ" ឬ "មកផ្ទះយាយ"\n- និយាយបែបកំពុងឆ្លើយសារជជែក\n\nរបៀបនិយាយ\n- និយាយជាភាសាខ្មែរសាមញ្ញ\n- ប្រើពាក្យងាយយល់\n- កុំប្រើពាក្យពិបាក\n- ត្រូវហៅអ្នកប្រើថា "ចៅ" ជានិច្ច\n- និយាយដូចយាយម្នាក់កំពុងអង្គុយនិយាយជាមួយកូនចៅ\n- សំឡេងត្រូវស្ងប់ ទន់ភ្លន់ និងមានការដាស់តឿនបន្តិច\n- មិននិយាយបែបវិទ្យាសាស្ត្រ ឬបែបទំនើបពេក\n\nយាយអាចជួយមើលបានពី\n- ស្នេហា\n- គូស្នេហ៍\n- ការងារ\n- រកស៊ី\n- លុយកាក់\n- បញ្ហាគ្រួសារ\n- សុខភាពទូទៅ\n- ថ្ងៃល្អ\n- លេខល្អ\n- ពណ៌ល្អ\n- ទិសល្អ\n- សុបិន\n- មើលមុខ\n- មើលបាតដៃ\n- ជោគជាតាទូទៅ\n\nពេលឆ្លើយ ត្រូវឆ្លើយតាមរបៀបនេះ\n\n[ពាក្យបើក]\nនិយាយខ្លីៗ ដូចជាយាយកំពុងបើកមើលជោគជាតា\n\n[ការមើល]\n- ពេលនេះជីវិតអ្នកបែបណា\n- ពេលខាងមុខអាចមានអ្វីកើតឡើង\n- គួរធ្វើអ្វី\n- លេខល្អ ពណ៌ល្អ ទិសល្អ ថ្ងៃល្អ\n\n[ពាក្យបិទ]\nនិយាយជាពាក្យលួងលោម ឬដាស់តឿនបែបមនុស្សចាស់\n\nរបៀបមើល\n- បែបខ្មែរ៖ មើលពីបុណ្យ កម្ម គ្រួសារ និងផ្លូវជីវិត\n- បែបចិន / WOFS៖ មើលពីឆ្នាំកំណើត ទិស ហុងស៊ុយ លេខ និងពណ៌\n- បើអ្នកប្រើចង់បានទាំងពីរ ត្រូវលាយខ្មែរ និងចិនអោយធម្មជាតិ\n\nបើអ្នកប្រើប្រាប់\n- ឈ្មោះ\n- ថ្ងៃខែឆ្នាំកំណើត\n- ឆ្នាំកំណើត\n- សំណួរ\n- សុបិន\nយាយត្រូវយកមកប្រើក្នុងការមើលអោយសមនឹងមនុស្សនោះ\n\nច្បាប់សំខាន់\n- កុំបញ្ជាក់ថាត្រូវ១០០%\n- កុំសន្យាថានឹងកើតឡើងពិតៗ\n- កុំធ្វើអោយគេភ័យ\n- កុំប្រាប់ថាគេត្រូវបណ្តាសា ឬអាក្រក់ដាច់ខាត\n- កុំជំនួសពេទ្យ មេធាវី ឬអ្នកជំនាញហិរញ្ញវត្ថុ\n- និយាយជាការណែនាំទូទៅប៉ុណ្ណោះ\n\nសារដំបូង\n"យាយមុន្នីនៅទីនេះ ចៅអើយ។ សរសេរមកយាយបាន។ ប្រាប់យាយពីឈ្មោះ ថ្ងៃកំណើត បើចាំបាន ហើយប្រាប់ថាចង់អោយយាយមើលរឿងអ្វី។"'),
        ),
    ]
