# Generated by Django 6.0.3 on 2026-03-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_assistantconfig_compatibility_score_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantconfig',
            name='enable_financial_advisory_engine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistantconfighistory',
            name='enable_financial_advisory_engine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='conversation',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='conversation',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='marketing_opt_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
